### ISSUE TITLE
unexpected golf:script behaviour 

### ISSUE THREAD

**Issue by kesar** [primitivefinance/hardhat-marmite#7]
My script:

```
import hre from 'hardhat';
import marmite from '@primitivefi/hardhat-marmite';

async function main() {
    await marmite(hre, async (flag) => {
        const Complex = await hre.ethers.getContractFactory('Complex');
        const complex = await Complex.deploy(1);

        const tx = await complex.set(42);
        await flag('Set function', tx);
    });
}

main();
``` 

contract:
```
// SPDX-License-Identifier: WTFPL
pragma solidity 0.8.9;

contract Complex {
    uint256 public bar;

    constructor(uint256 initBar) {
        bar = initBar;
    }

    function set(uint256 newBar) external {
        @start<test1>
        if (newBar > 0) {
            bar = newBar;
        }
        @end

        @start<test2>
        if (newBar != 0) {
            bar = newBar;
        }
        @end
    }
}
``` 

executing: npx hardhat golf:script ./scripts/marmite.ts

returns:

![image](https://user-images.githubusercontent.com/1288106/149544797-5781dc40-56a7-42d7-96fe-8a04ded75ea0.png)

Greater-than    │    Different-from are from another contract in the same folder than Complex

I would expect return only from the contract I am running in the script

**Comment by clemlak** [comment]
Thank you for using Marmite! :)

Regarding your issue, this behavior is actually explained in the README: if you don't provide any implementation names to the `marmite` function, the task will go through all the implementations it finds in your contracts.

The correct way to avoid this is to specify the implementations you want to compare:

```typescript
import hre from 'hardhat';
import marmite from '@primitivefi/hardhat-marmite';

async function main() {
    await marmite(hre, async (flag) => {
        const Complex = await hre.ethers.getContractFactory('Complex');
        const complex = await Complex.deploy(1);

        const tx = await complex.set(42);
        await flag('Set function', tx);
    }, ['test1', 'test2']);
}

main();
```

I'm closing this issue since it's not related to a bug, but if you find a better way to handle things feel free to create a new one!

**Comment by kesar** [comment]
makes sense! thanks!
